In [1]:
import numpy as np

## Creating Numpy Arrays

### Creating a 1D Numpy Array from a List

In [15]:
arr1=np.array([1,2,3,4,5])
print(arr1)
print("the shape of 1D array  : \n",arr1.shape)

[1 2 3 4 5]
the shape of 1D array  : 
 (5,)


### Creating a 2D Numpy Array from a List of Lists

In [14]:
arr2=np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print("the shape of 2D array  : \n",arr2.shape)

[[1 2 3 4]
 [1 2 3 4]]
the shape of 2D array  : 
 (2, 4)


### Suppose you want to store sales data for three products over four weeks across two regions. This can be represented as a 3D array where:
1. Axis 0: Weeks (4 weeks).
2. Axis 1: Regions (2 regions).
3. Axis 2: Products (3 products).
Using NumPy, you can create this 3D array as follows:


In [13]:
# 3D array= 4 weeks * 2 regions * 3 products
sales_data=np.array([
                    [[140,150,160],[140,150,160]], #week1
                    [[140,150,160],[140,150,160]], #week2
                    [[140,150,160],[140,150,160]], #week3
                    [[140,150,160],[140,150,160]] #week4
                    ]) #week4
print("sales data : \n",sales_data)
print("the shape of 3D array : \n",sales_data.shape)

sales data : 
 [[[140 150 160]
  [140 150 160]]

 [[140 150 160]
  [140 150 160]]

 [[140 150 160]
  [140 150 160]]

 [[140 150 160]
  [140 150 160]]]
the shape of 3D array : 
 (4, 2, 3)


### Creating an Array of Zeros


In [17]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


### Creating an Array of Ones


In [19]:
ones=np.ones((4,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Creating an Array with a Specific Range

In [20]:
range_array=np.arange(1,11)
print(range_array)

[ 1  2  3  4  5  6  7  8  9 10]


### Creating an Array of Evenly Spaced Values Between Two Numbers


In [21]:
linspace_array=np.linspace(0,1,5)
print(linspace_array)

[0.   0.25 0.5  0.75 1.  ]


### Creating an Array with Random Values Between 0 and 1


In [22]:
random_array=np.random.rand(3,3)
print(random_array)

[[0.1809409  0.45402384 0.91425504]
 [0.14994932 0.59843886 0.00113811]
 [0.00583703 0.39353694 0.33523844]]


### Creating an Array with Random Integers


In [24]:
random_integers=np.random.randint(1,10,(2,2))
print(random_integers)

[[3 9]
 [2 6]]


### Checking the Shape of an Array


In [25]:
arr2=np.array([[1,2,3,4],[1,2,3,4]])
print("the shape of 2D array  : \n",arr2.shape)

the shape of 2D array  : 
 (2, 4)


### Accessing Data Type of Elements

In [26]:
print(arr2.dtype)

int64


### Indexing a 1D Array


In [27]:
arr1=np.array([1,2,3,4,5])
print(arr1[0])
print(arr1[2])

1
3


### Slicing a 1D Array


In [28]:
print(arr1[:2])

[1 2]


### Indexing a 2D Array

In [32]:
arr2=np.array([[1,2,3,4],[8,5,6,7]])
print(arr2[1,2]) # array[row,col]
# or 
print(arr2[1][2])# array[row][col]

6
6


### Slicing a 2D Array

In [37]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
# shape top row
arr2[0]

array([1, 2, 3])

In [39]:
# shape (2,2) from bottom left corner
arr2[1:,:2]

array([[4, 5],
       [7, 8]])

In [40]:
# shape bottom row
arr2[2]

array([7, 8, 9])

In [41]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], 
              [8, 9, 10, 11, 12, 13, 14]])
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# Get a specific element [row, column]
a[1, 5]  # to select element '13' we need row 2 and element 6. Hence r=1, c=5 (index start from 0)
# or a[1, -2]

np.int64(13)

In [43]:

# Get a specific row
a[0, :]  # all columns

array([1, 2, 3, 4, 5, 6, 7])

In [44]:
# Get a specific column
a[:, 2]  # all rows

array([ 3, 10])

In [45]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

### Boolean array indexing

In [2]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
bool_a=a>4
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Element-wise Addition

In [ ]:
arr1=np.arange(1,6)  # 1 2 3 4 5
arr2=np.arange(6,11) # 6 7 8 9 10
print(arr1+arr2)

[ 7  9 11 13 15]


### Universal Array Functions (Mathematical operations)


In [23]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x)
print(y)


[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [22]:
# Elementwise sum; both produce the array
print(x + y)
# or
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [21]:
# Elementwise difference; both produce the array
print(x - y)
# or
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [20]:
# Elementwise product; both produce the array
print(x * y)
# or
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [19]:
# Elementwise division; both produce the array
print(x / y)
# or
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
# Dot product: product of two arrays
f = np.array([1, 2])
g = np.array([4, 5])

# 1*4 + 2*5 = 14
print(np.dot(f, g))

14


### Array Broadcasting


Broadcasting allows arithmetic operations on arrays of different shapes. Here, 10 is added to each element of the array.


In [25]:
array=np.arange(1,6)
print("array before operation : ",array)
print("array after operation : ",array+10)


array before operation :  [1 2 3 4 5]
array after operation :  [11 12 13 14 15]


For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [26]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9], 
              [10, 11, 12]])

v = np.array([1, 0, 1])

y = np.empty_like(x)  # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(x)
print("================")
print(y)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### Matrix Multiplication


In [30]:
arr1=np.array([[1,2],[4,5]])
arr2=np.array([[1,2],[4,5]])
print(np.dot(arr1,arr2))

[[ 9 12]
 [24 33]]


### Calculating Mean and Sum


In [31]:
arr1=np.arange(1,6) 
print(np.mean(arr1))
print(np.sum(arr1))

3.0
15


### Finding Maximum and Minimum Values


In [32]:
arr1=np.arange(1,6) 
print(np.max(arr1))
print(np.min(arr1))

5
1


In [39]:
# Generate matrix
matrix = np.arange(1, 31).reshape(6, 5)
print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [37]:
# Extracting [[11, 12], [16, 17]]
submatrix_1 = matrix[2:4, 0:2]  #
print(submatrix_1)

[[11 12]
 [16 17]]


In [38]:
# Accessing elements diagonally
diagonal_matrix = np.zeros_like(matrix, dtype=float)  # Create zero matrix
indices = [0, 1, 2, 3]  # Diagonal positions
diagonal_values = [2, 8, 14, 20]  # Values at these positions

for i, val in zip(indices, diagonal_values):
    diagonal_matrix[i, i] = val
print(diagonal_matrix)

[[ 2.  0.  0.  0.  0.]
 [ 0.  8.  0.  0.  0.]
 [ 0.  0. 14.  0.  0.]
 [ 0.  0.  0. 20.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [40]:
# Accessing specific rows and columns
access_matrix = np.zeros_like(matrix, dtype=float)  # Create zero matrix
access_matrix[0, 3:5] = matrix[0, 3:5]  # Extracting [4, 5]
access_matrix[4, 3:5] = matrix[4, 3:5]  # Extracting [24, 25]
access_matrix[5, 3:5] = matrix[5, 3:5]  # Extracting [29, 30]

print(access_matrix)

[[ 0.  0.  0.  4.  5.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0. 24. 25.]
 [ 0.  0.  0. 29. 30.]]
